// <auto-generated />
using System;
using CGServer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CGServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CGEntity.EntitiesDbSet.DbSetCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("CGEntity.EntitiesDbSet.DbSetFavorecido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Favorecidos");
                });

            modelBuilder.Entity("CGEntity.EntitiesDbSet.DbSetFornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("CGEntity.EntitiesDbSet.DbSetInstituicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Instituicoes");
                });

            modelBuilder.Entity("CGEntity.EntitiesDbSet.DbSetLancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FavorecidoId")
                        .HasColumnType("int");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<int>("InstituicaoId")
                        .HasColumnType("int");

                    b.Property<int>("ModalidadeId")
                        .HasColumnType("int");

                    b.Property<int>("PagadorId")
                        .HasColumnType("int");

                    b.Property<bool>("Recorrente")
                        .HasColumnType("bit");

                    b.Property<int?>("SubCategoriaId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("FavorecidoId");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("InstituicaoId");

                    b.HasIndex("ModalidadeId");

                    b.HasIndex("PagadorId");

                    b.HasIndex("SubCategoriaId");

                    b.ToTable("Lancamentos");
                });

            modelBuilder.Entity("CGEntity.EntitiesDbSet.DbSetModalidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Modalidades");
                });

            modelBuilder.Entity("CGEntity.EntitiesDbSet.DbSetPagador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Pagadores");
                });

            modelBuilder.Entity("CGEntity.EntitiesDbSet.DbSetSubCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("SubCategorias");
                });

            modelBuilder.Entity("CGEntity.EntitiesDbSet.DbSetLancamento", b =>
                {
                    b.HasOne("CGEntity.EntitiesDbSet.DbSetCategoria", "Categoria")
                        .WithMany("Lancamentos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGEntity.EntitiesDbSet.DbSetFavorecido", "Favorecido")
                        .WithMany("Lancamentos")
                        .HasForeignKey("FavorecidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGEntity.EntitiesDbSet.DbSetFornecedor", "Fornecedor")
                        .WithMany("Lancamentos")
                        .HasForeignKey("FornecedorId");

                    b.HasOne("CGEntity.EntitiesDbSet.DbSetInstituicao", "Instituicao")
                        .WithMany("Lancamentos")
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGEntity.EntitiesDbSet.DbSetModalidade", "Modalidade")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ModalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGEntity.EntitiesDbSet.DbSetPagador", "Pagador")
                        .WithMany("Lancamentos")
                        .HasForeignKey("PagadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGEntity.EntitiesDbSet.DbSetSubCategoria", "SubCategoria")
                        .WithMany("Lancamentos")
                        .HasForeignKey("SubCategoriaId");

                    b.Navigation("Categoria");

                    b.Navigation("Favorecido");

                    b.Navigation("Fornecedor");

                    b.Navigation("Instituicao");

                    b.Navigation("Modalidade");

                    b.Navigation("Pagador");

                    b.Navigation("SubCategoria");
                });

            modelBuilder.Entity("CGEntity.EntitiesDbSet.DbSetSubCategoria", b =>
                {
                    b.HasOne("CGEntity.EntitiesDbSet.DbSetCategoria", "Categoria")
                        .WithMany("SubCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CGEntity.EntitiesDbSet.DbSetCategoria", b =>
                {
                    b.Navigation("Lancamentos");

                    b.Navigation("SubCategorias");
                });

            modelBuilder.Entity("CGEntity.EntitiesDbSet.DbSetFavorecido", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("CGEntity.EntitiesDbSet.DbSetFornecedor", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("CGEntity.EntitiesDbSet.DbSetInstituicao", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("CGEntity.EntitiesDbSet.DbSetModalidade", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("CGEntity.EntitiesDbSet.DbSetPagador", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("CGEntity.EntitiesDbSet.DbSetSubCategoria", b =>
                {
                    b.Navigation("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
